id: PC8B7F501
initial_creation_type: ocr
source_metadata:
  volumes:
    fec68cfc69a449798432460ed164459d:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: བགེགས་བསྐྲད་པའི་སྒྲུབ་པའི་ཐབས།
      total_pages: 1648
      volume_number: 40
